name: Deploy to PyPI

on: push

jobs:
  build-n-publish:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8
      - name: Install build tools
        run: |
          python -m pip install build setuptools_scm wheel
          conda install -c conda-forge numpy cython pyfftw
      - name: Build a source tarball
        run: python -m build --no-isolation
      - name: Build a manylinux binary wheel
        uses: RalfG/python-wheels-manylinux-build@v0.3.4-manylinux2014_x86_64
        with:
          python-versions: 'cp37-cp37m cp38-cp38'
          #python-versions: 'cp37-cp37m cp38-cp38 cp39-cp39'
          build-requirements: 'cython numpy setuptools pyfftw'
      - name: Copy manylinux wheel into the dist directory
        run: |
          mkdir dist_manylinux/
          cp dist/*manylinux*.whl dist_manylinux/
          cp dist/*.tar.gz dist_manylinux/
      # deploy to Test PyPI on any push except when merging to master, since that will
      # already exist, and thus fail.
      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_TEST_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          packages_dir: dist_manylinux/
          skip_existing: true
      # deploy to actual PyPI only when a tag is pushed to main
      - name: Publish distribution to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: dist_manylinux/
          skip_existing: true
