name: Deploy to PyPI

on: push

jobs:
  build-n-publish:
    name: Deploy
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@main
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install build tools
        run: |
          python -m pip install setuptools_scm build wheel
          python -m pip install numpy scipy pyfftw cython
          python setup.py --version
      - name: Build a binary wheel and a source tarball
        run: python -m build --no-isolation
      # deploy to Test PyPI on any push except when merging to master, since that will
      # already exist, and thus fail.
      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_TEST_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
      # deploy to actual PyPI only when a tag is pushed to main
      - name: Publish distribution to PyPI
        if: startsWith(github.event.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
